AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'lib/tasks/*'
    - 'script/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

