services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - database
      - redis
      - idedit
      - sidekiq
    ports: 
      - 3000:3000
    volumes:
      - ./:/root/app/
      - gemdata:/bundle
    environment: 
      - RAILS_ENV=docker
      - IDEDIT_URL="http://idedit:2000"
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - POSTGRES_PASSWORD
      - RAILS_MASTER_KEY=2f28c42b30b5613178b01aee71776139
    entrypoint: ./entrypoints/app.sh

  redis:
    image: redis:7.0.0-alpine

  idedit:
    build: 
      context: https://github.com/h4ppyr0gu3/idedit.git

  database: 
    environment: 
      - POSTGRES_PASSWORD=postgres
    image: postgres:14.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - REDIS_URL=redis
      - POSTGRES_PASSWORD
      - IDEDIT_URL="http://idedit:2000"
      - REDIS_PORT=6379
      - RAILS_MASTER_KEY=2f28c42b30b5613178b01aee71776139
    depends_on:     
      - database
      - redis
    volumes:
      - ./:/root/app/
      - gemdata:/bundle
    entrypoint: ./entrypoints/sidekiq.sh

volumes:
  pgdata:
  .:
  gemdata:
