production:
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  # url: <%= ENV.fetch("POSTGRES_PROD_URL") { "postgres://postgres:postgres@localhost:5432/mapp_dev" } %>
  url: <%= ENV.fetch("POSTGRES_DEV_URL") { "postgres://david:postgres@localhost:5432/mapp_prod" } %>

development:
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # url: <%= ENV.fetch("POSTGRES_DEV_URL") { "postgres://david:postgres@localhost:5432/mapp_prod" } %>
  host: localhost
  port: 5432
  password: postgres
  username: postgres
  database: mapp_dev

test:
  encoding: unicode
  adapter: postgresql
  password: postgres
  username: postgres
  host: localhost
  port: 5432
  database: mapp_test

docker: 
  encoding: unicode
  adapter: postgresql
  database: mapp_docker
  host: localhost
  port: 5432
  username: postgres
  password: postgres
