production:
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  url: <%= ENV.fetch("POSTGRES_PROD_URL") %>

development:
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("POSTGRES_DEV_URL") %>

test:
  encoding: unicode
  adapter: postgresql
  password: postgres
  username: postgres
  host: localhost
  port: 5432

docker: 
  encoding: unicode
  adapter: postgresql
  database: mapp_docker
  host: localhost
  port: 5432
  username: postgres
  password: postgres
