name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  build:
    runs_on: ruby:3.1.2
    steps:
      - uses: actions/checkout@v3
      - run: "apt-get install -y build-essential docker docker-compose"
      - run: "docker-compose up"
